"""Generate thesaurus.json for the AI Paraphrasing Tool with mode-based synonym groups."""
import json, os, math, random

random.seed(42)

FLAT_THESAURUS = {
    "good": ["excellent", "superior", "fine", "positive", "favorable", "satisfactory"],
    "bad": ["poor", "inferior", "unfavorable", "negative", "substandard", "unsatisfactory"],
    "big": ["large", "substantial", "considerable", "massive", "enormous", "immense"],
    "small": ["tiny", "compact", "minor", "minimal", "modest", "diminutive"],
    "great": ["remarkable", "outstanding", "exceptional", "impressive", "magnificent"],
    "important": ["significant", "crucial", "vital", "essential", "critical", "paramount"],
    "fast": ["quick", "rapid", "swift", "speedy", "brisk", "hasty"],
    "slow": ["gradual", "leisurely", "sluggish", "unhurried", "moderate"],
    "new": ["fresh", "recent", "modern", "novel", "contemporary", "current"],
    "old": ["aged", "ancient", "vintage", "antique", "elderly", "former"],
    "easy": ["simple", "straightforward", "effortless", "uncomplicated", "basic"],
    "hard": ["difficult", "challenging", "tough", "demanding", "arduous"],
    "strong": ["powerful", "robust", "sturdy", "durable", "resilient", "vigorous"],
    "weak": ["feeble", "frail", "fragile", "delicate", "vulnerable", "faint"],
    "true": ["accurate", "correct", "genuine", "authentic", "valid", "factual"],
    "false": ["incorrect", "inaccurate", "misleading", "untrue", "fabricated"],
    "help": ["assist", "support", "aid", "facilitate", "guide", "serve"],
    "change": ["modify", "adjust", "alter", "transform", "convert", "revise"],
    "use": ["utilize", "employ", "apply", "leverage", "harness", "exercise"],
    "make": ["create", "produce", "generate", "construct", "build", "form"],
    "get": ["obtain", "acquire", "secure", "attain", "procure", "receive"],
    "give": ["provide", "offer", "supply", "deliver", "grant", "present"],
    "take": ["acquire", "obtain", "seize", "grasp", "capture", "collect"],
    "find": ["discover", "locate", "uncover", "detect", "identify", "determine"],
    "show": ["demonstrate", "display", "exhibit", "reveal", "indicate", "present"],
    "keep": ["maintain", "preserve", "retain", "sustain", "continue", "protect"],
    "need": ["require", "demand", "necessitate", "call for", "want", "lack"],
    "know": ["understand", "comprehend", "recognize", "realize", "perceive"],
    "think": ["believe", "consider", "suppose", "assume", "deem", "judge"],
    "want": ["desire", "wish", "seek", "pursue", "prefer", "favor"],
    "work": ["function", "operate", "perform", "labour", "toil", "strive"],
    "start": ["begin", "commence", "initiate", "launch", "embark on", "undertake"],
    "end": ["finish", "conclude", "terminate", "complete", "cease", "halt"],
    "try": ["attempt", "endeavor", "strive", "seek", "aim", "undertake"],
    "move": ["shift", "transfer", "relocate", "transport", "advance", "proceed"],
    "bring": ["carry", "convey", "transport", "deliver", "fetch", "escort"],
    "buy": ["purchase", "acquire", "obtain", "procure", "invest in", "pay for"],
    "sell": ["vend", "market", "trade", "offer", "dispose of", "merchandise"],
    "build": ["construct", "assemble", "erect", "establish", "create", "develop"],
    "grow": ["expand", "increase", "develop", "flourish", "thrive", "prosper"],
    "improve": ["enhance", "upgrade", "better", "refine", "optimize", "advance"],
    "reduce": ["decrease", "diminish", "lower", "lessen", "cut", "minimize"],
    "increase": ["boost", "expand", "raise", "augment", "amplify", "magnify"],
    "develop": ["evolve", "advance", "progress", "cultivate", "foster", "grow"],
    "support": ["uphold", "back", "sustain", "bolster", "reinforce", "advocate"],
    "include": ["contain", "comprise", "encompass", "involve", "incorporate", "embody"],
    "provide": ["furnish", "supply", "offer", "equip", "outfit", "allocate"],
    "manage": ["oversee", "supervise", "administer", "direct", "govern", "coordinate"],
    "create": ["generate", "produce", "establish", "compose", "invent", "originate"],
    "describe": ["portray", "depict", "characterize", "outline", "illustrate", "represent"],
    "explain": ["clarify", "elucidate", "illuminate", "interpret", "expound", "explicate"],
    "consider": ["contemplate", "examine", "evaluate", "assess", "deliberate", "ponder"],
    "suggest": ["propose", "recommend", "advise", "advocate", "recommend", "submit"],
    "analyze": ["examine", "evaluate", "study", "assess", "scrutinize", "investigate"],
    "discuss": ["examine", "debate", "explore", "deliberate", "review", "consider"],
    "result": ["outcome", "consequence", "effect", "product", "yield", "output"],
    "cause": ["reason", "source", "origin", "basis", "catalyst", "factor"],
    "effect": ["impact", "influence", "outcome", "result", "consequence", "ramification"],
    "problem": ["issue", "challenge", "difficulty", "obstacle", "dilemma", "hardship"],
    "solution": ["answer", "resolution", "remedy", "fix", "cure", "response"],
    "example": ["instance", "illustration", "sample", "case", "specimen", "demonstration"],
    "method": ["approach", "technique", "process", "procedure", "system", "strategy"],
    "type": ["kind", "category", "variety", "classification", "genre", "sort"],
    "part": ["portion", "segment", "component", "element", "piece", "fraction"],
    "group": ["collection", "set", "cluster", "batch", "category", "assembly"],
    "system": ["framework", "structure", "organization", "network", "setup", "apparatus"],
    "process": ["procedure", "method", "system", "operation", "workflow", "approach"],
    "area": ["region", "zone", "sector", "territory", "district", "field"],
    "place": ["location", "site", "position", "spot", "venue", "setting"],
    "time": ["duration", "period", "span", "interval", "term", "phase"],
    "way": ["method", "approach", "manner", "means", "technique", "mode"],
    "thing": ["object", "item", "element", "entity", "article", "matter"],
    "person": ["individual", "human", "somebody", "being", "character", "figure"],
    "people": ["individuals", "persons", "humans", "public", "society", "community"],
    "company": ["organization", "corporation", "firm", "enterprise", "business", "establishment"],
    "business": ["enterprise", "venture", "operation", "organization", "commerce", "trade"],
    "project": ["initiative", "endeavor", "undertaking", "venture", "enterprise", "scheme"],
    "task": ["assignment", "job", "chore", "duty", "responsibility", "mission"],
    "plan": ["strategy", "scheme", "blueprint", "design", "program", "approach"],
    "goal": ["objective", "target", "aim", "purpose", "ambition", "aspiration"],
    "idea": ["concept", "notion", "thought", "suggestion", "proposal", "perception"],
    "view": ["perspective", "opinion", "standpoint", "outlook", "angle", "position"],
    "point": ["aspect", "detail", "factor", "element", "feature", "matter"],
    "value": ["worth", "merit", "significance", "importance", "benefit", "advantage"],
    "cost": ["price", "expense", "fee", "charge", "rate", "amount"],
    "benefit": ["advantage", "gain", "profit", "asset", "reward", "perk"],
    "risk": ["danger", "hazard", "threat", "peril", "exposure", "liability"],
    "quality": ["standard", "grade", "caliber", "excellence", "merit", "virtue"],
    "amount": ["quantity", "volume", "number", "mass", "bulk", "sum"],
    "level": ["degree", "extent", "stage", "grade", "rank", "tier"],
    "rate": ["speed", "pace", "frequency", "ratio", "proportion", "percentage"],
    "state": ["condition", "status", "situation", "circumstance", "position"],
    "order": ["arrangement", "sequence", "structure", "organization", "system"],
    "control": ["regulate", "manage", "direct", "govern", "supervise", "command"],
    "check": ["verify", "confirm", "validate", "inspect", "examine", "review"],
    "test": ["evaluate", "assess", "verify", "trial", "pilot", "experiment"],
    "measure": ["quantify", "gauge", "assess", "calculate", "determine", "evaluate"],
    "compare": ["contrast", "evaluate", "differentiate", "distinguish", "relate"],
    "select": ["choose", "pick", "opt for", "designate", "elect", "prefer"],
    "decide": ["determine", "resolve", "conclude", "settle", "choose", "judge"],
    "allow": ["permit", "authorize", "enable", "grant", "approve", "sanction"],
    "require": ["demand", "necessitate", "mandate", "obligate", "compel", "stipulate"],
    "prevent": ["avoid", "hinder", "impede", "inhibit", "obstruct", "thwart"],
    "protect": ["defend", "shield", "safeguard", "secure", "guard", "preserve"],
    "ensure": ["guarantee", "assure", "certify", "confirm", "verify", "warrant"],
    "establish": ["found", "create", "form", "set up", "institute", "organize"],
    "achieve": ["accomplish", "attain", "realize", "fulfill", "complete", "reach"],
    "maintain": ["preserve", "sustain", "uphold", "continue", "retain", "perpetuate"],
    "operate": ["function", "run", "conduct", "manage", "perform", "execute"],
    "produce": ["generate", "manufacture", "create", "yield", "develop", "output"],
    "perform": ["execute", "conduct", "accomplish", "carry out", "fulfill"],
    "follow": ["pursue", "track", "trail", "chase", "shadow", "monitor"],
    "lead": ["guide", "direct", "steer", "conduct", "usher", "pilot"],
    "set": ["establish", "determine", "assign", "specify", "designate", "fix"],
    "put": ["place", "position", "set", "deposit", "install", "situate"],
    "come": ["arrive", "approach", "appear", "emerge", "materialize", "occur"],
    "go": ["proceed", "depart", "move", "travel", "advance", "venture"],
    "see": ["observe", "witness", "notice", "perceive", "discern", "detect"],
    "look": ["examine", "observe", "survey", "view", "inspect", "scrutinize"],
    "hear": ["listen", "perceive", "detect", "overhear", "attend", "eavesdrop"],
    "speak": ["talk", "communicate", "utter", "express", "declare", "articulate"],
    "say": ["state", "declare", "mention", "remark", "assert", "express"],
    "tell": ["inform", "notify", "advise", "apprise", "brief", "disclose"],
    "ask": ["inquire", "question", "query", "request", "solicit", "interrogate"],
    "answer": ["reply", "respond", "react", "retort", "counter", "rejoin"],
    "call": ["summon", "contact", "phone", "ring", "page", "convene"],
    "write": ["compose", "draft", "pen", "author", "inscribe", "record"],
    "read": ["peruse", "scan", "browse", "study", "review", "examine"],
    "learn": ["study", "acquire", "grasp", "master", "absorb", "assimilate"],
    "teach": ["instruct", "educate", "train", "tutor", "coach", "enlighten"],
    "train": ["coach", "tutor", "instruct", "drill", "educate", "prepare"],
    "study": ["examine", "analyze", "investigate", "research", "explore", "review"],
    "research": ["investigate", "explore", "study", "examine", "analyze", "probe"],
    "review": ["evaluate", "assess", "appraise", "examine", "scrutinize", "critique"],
    "report": ["document", "record", "account", "narrative", "summary", "brief"],
    "record": ["document", "register", "log", "file", "note", "chronicle"],
    "list": ["catalog", "enumerate", "itemize", "schedule", "register", "index"],
    "mark": ["indicate", "designate", "label", "identify", "distinguish", "characterize"],
    "sign": ["indicator", "symbol", "signal", "mark", "token", "evidence"],
    "letter": ["correspondence", "message", "communication", "note", "dispatch"],
    "document": ["record", "report", "file", "paper", "manuscript", "certificate"],
    "form": ["shape", "structure", "configuration", "arrangement", "format", "design"],
    "model": ["prototype", "framework", "template", "pattern", "blueprint"],
    "standard": ["benchmark", "criterion", "guideline", "norm", "yardstick", "measure"],
    "rule": ["regulation", "guideline", "principle", "policy", "directive", "protocol"],
    "law": ["regulation", "statute", "ordinance", "decree", "legislation", "rule"],
    "right": ["entitlement", "privilege", "prerogative", "claim", "authority"],
    "duty": ["obligation", "responsibility", "commitment", "accountability", "burden"],
    "role": ["function", "position", "capacity", "part", "responsibility", "task"],
    "job": ["position", "occupation", "profession", "career", "vocation", "post"],
    "skill": ["ability", "expertise", "proficiency", "competence", "aptitude", "talent"],
    "knowledge": ["understanding", "expertise", "proficiency", "wisdom", "insight"],
    "experience": ["exposure", "background", "history", "track record", "practice"],
    "education": ["learning", "training", "instruction", "schooling", "tuition"],
    "health": ["wellness", "fitness", "condition", "welfare", "vitality", "vigor"],
    "care": ["concern", "attention", "consideration", "regard", "diligence"],
    "safety": ["security", "protection", "wellbeing", "safeguard", "preservation"],
    "security": ["safety", "protection", "defense", "safeguard", "assurance"],
    "peace": ["calm", "tranquility", "harmony", "serenity", "stillness", "quiet"],
    "war": ["conflict", "battle", "combat", "warfare", "struggle", "clash"],
    "love": ["affection", "devotion", "admiration", "fondness", "adoration"],
    "hate": ["detest", "loathe", "abhor", "despise", "dislike", "reject"],
    "happy": ["joyful", "content", "pleased", "delighted", "cheerful", "elated"],
    "sad": ["unhappy", "sorrowful", "melancholy", "mournful", "gloomy", "dejected"],
    "angry": ["furious", "irate", "outraged", "enraged", "livid", "incensed"],
    "calm": ["serene", "tranquil", "peaceful", "placid", "composed", "collected"],
    "clear": ["obvious", "evident", "apparent", "transparent", "distinct", "plain"],
    "bright": ["brilliant", "luminous", "radiant", "vivid", "shining", "glowing"],
    "dark": ["gloomy", "dim", "shadowy", "murky", "obscure", "somber"],
    "light": ["bright", "illuminated", "luminous", "radiant", "shining", "glowing"],
    "heavy": ["weighty", "substantial", "massive", "dense", "burdensome"],
    "full": ["complete", "entire", "total", "maximum", "saturated", "packed"],
    "empty": ["vacant", "void", "barren", "blank", "hollow", "unoccupied"],
    "open": ["accessible", "available", "public", "exposed", "visible", "unrestricted"],
    "closed": ["shut", "sealed", "secured", "locked", "blocked", "restricted"],
    "high": ["elevated", "lofty", "tall", "soaring", "towering", "sky-high"],
    "low": ["minimal", "reduced", "moderate", "limited", "depressed", "diminished"],
    "deep": ["profound", "intense", "extreme", "significant", "thorough", "comprehensive"],
    "short": ["brief", "concise", "succinct", "compact", "abbreviated", "limited"],
    "long": ["extended", "lengthy", "prolonged", "sustained", "lasting", "extensive"],
    "wide": ["broad", "extensive", "expansive", "vast", "ample", "spacious"],
    "narrow": ["limited", "restricted", "confined", "slim", "tight", "constructed"],
    "rich": ["wealthy", "affluent", "prosperous", "well-off", "opulent", "lavish"],
    "poor": ["needy", "impoverished", "destitute", "underprivileged", "disadvantaged"],
    "free": ["complimentary", "gratis", "liberated", "unrestricted", "independent"],
    "cheap": ["inexpensive", "affordable", "budget", "economical", "low-cost"],
    "expensive": ["costly", "pricey", "premium", "exorbitant", "overpriced", "high-end"],
    "beautiful": ["gorgeous", "stunning", "magnificent", "picturesque", "elegant"],
    "ugly": ["unsightly", "hideous", "unattractive", "repulsive", "grotesque"],
    "modern": ["contemporary", "current", "up-to-date", "innovative", "trendy"],
    "traditional": ["conventional", "orthodox", "classic", "established", "customary"],
    "simple": ["basic", "straightforward", "plain", "uncomplicated", "elementary"],
    "complex": ["complicated", "intricate", "sophisticated", "elaborate", "multifaceted"],
    "common": ["frequent", "widespread", "prevalent", "ordinary", "typical", "standard"],
    "rare": ["uncommon", "scarce", "infrequent", "unusual", "exceptional", "unique"],
    "special": ["distinctive", "exceptional", "unique", "extraordinary", "notable"],
    "regular": ["routine", "standard", "typical", "normal", "usual", "ordinary"],
    "normal": ["standard", "typical", "ordinary", "conventional", "regular", "usual"],
    "usual": ["customary", "habitual", "typical", "normal", "ordinary", "routine"],
    "necessary": ["essential", "required", "indispensable", "compulsory", "mandatory"],
    "possible": ["feasible", "achievable", "attainable", "viable", "realizable"],
    "likely": ["probable", "expected", "plausible", "reasonable", "anticipated"],
    "certain": ["definite", "assured", "guaranteed", "unquestionable", "absolute"],
    "specific": ["particular", "distinct", "precise", "exact", "definite", "explicit"],
    "general": ["overall", "broad", "comprehensive", "universal", "sweeping"],
    "main": ["primary", "principal", "chief", "key", "leading", "foremost"],
    "major": ["significant", "substantial", "considerable", "primary", "principal"],
    "minor": ["lesser", "secondary", "subordinate", "minimal", "negligible"],
    "basic": ["fundamental", "elementary", "essential", "primary", "underlying", "core"],
    "advanced": ["sophisticated", "complex", "high-level", "cutting-edge", "innovative"],
    "public": ["civic", "communal", "social", "municipal", "popular", "collective"],
    "private": ["confidential", "personal", "individual", "restricted", "exclusive"],
    "personal": ["individual", "private", "intimate", "subjective", "customized"],
    "social": ["communal", "public", "societal", "community", "shared", "collective"],
    "global": ["worldwide", "international", "universal", "planetary", "comprehensive"],
    "local": ["regional", "community", "neighborhood", "vicinity", "nearby"],
    "national": ["countrywide", "domestic", "federal", "statewide", "internal"],
    "international": ["global", "worldwide", "multinational", "intercontinental"],
    "natural": ["organic", "innate", "inherent", "native", "authentic", "unprocessed"],
    "artificial": ["synthetic", "man-made", "simulated", "manufactured", "fabricated"],
    "human": ["personal", "individual", "mortal", "social", "anthropoid"],
    "automatic": ["automated", "mechanical", "robotic", "self-acting", "programmed"],
    "manual": ["hand-operated", "physical", "human", "handmade", "by hand"],
    "active": ["dynamic", "energetic", "vigorous", "lively", "animated", "engaged"],
    "passive": ["inactive", "idle", "inert", "dormant", "receptive", "submissive"],
    "positive": ["optimistic", "constructive", "favorable", "beneficial", "affirmative"],
    "negative": ["adverse", "harmful", "detrimental", "unfavorable", "damaging"],
    "potential": ["possible", "likely", "prospective", "latent", "future", "pending"],
    "actual": ["real", "genuine", "concrete", "substantive", "factual", "literal"],
    "entire": ["whole", "complete", "total", "full", "absolute", "comprehensive"],
    "partial": ["incomplete", "limited", "fractional", "segmented", "piecemeal"],
    "different": ["distinct", "diverse", "dissimilar", "varying", "contrasting", "unique"],
    "similar": ["alike", "comparable", "equivalent", "parallel", "analogous"],
    "same": ["identical", "equivalent", "equal", "matching", "twin", "duplicate"],
    "opposite": ["contrary", "reverse", "inverse", "antithetical", "conflicting"],
    "separate": ["distinct", "individual", "independent", "detached", "isolated"],
    "combined": ["united", "integrated", "merged", "consolidated", "collective"],
    "related": ["connected", "associated", "linked", "affiliated", "correlated"],
    "relevant": ["pertinent", "applicable", "appropriate", "germane", "material"],
    "useful": ["helpful", "practical", "valuable", "functional", "beneficial"],
    "useless": ["pointless", "futile", "vain", "ineffective", "inefficient"],
    "effective": ["efficient", "successful", "productive", "impactful", "potent"],
    "efficient": ["productive", "effective", "streamlined", "optimized", "economical"],
    "proper": ["appropriate", "correct", "suitable", "fitting", "adequate", "right"],
    "appropriate": ["suitable", "fitting", "proper", "relevant", "applicable"],
    "correct": ["accurate", "right", "precise", "exact", "proper", "flawless"],
    "exact": ["precise", "accurate", "specific", "explicit", "detailed", "minute"],
    "precise": ["exact", "accurate", "careful", "meticulous", "particular"],
    "fair": ["just", "equitable", "impartial", "objective", "unbiased"],
    "equal": ["identical", "equivalent", "uniform", "balanced", "matched"],
    "various": ["diverse", "assorted", "different", "numerous", "multiple", "sundry"],
    "multiple": ["numerous", "various", "manifold", "countless", "abundant"],
    "single": ["individual", "sole", "solitary", "unique", "singular", "exclusive"],
    "only": ["sole", "single", "exclusive", "unique", "alone", "singular"],
    "many": ["numerous", "countless", "multiple", "abundant", "copious", "plentiful"],
    "more": ["additional", "further", "supplementary", "extra", "added", "extended"],
    "less": ["fewer", "reduced", "diminished", "lower", "minimal", "inferior"],
    "most": ["maximum", "utmost", "majority", "greatest", "highest", "supreme"],
    "some": ["several", "a few", "various", "certain", "select", "particular"],
    "few": ["scant", "scarce", "limited", "minimal", "meager", "sparse"],
    "all": ["every", "each", "total", "entire", "complete", "whole"],
    "each": ["every", "individual", "separate", "respective", "particular"],
    "every": ["each", "all", "entire", "total", "complete", "whole"],
    "any": ["some", "whatever", "whichever", "anyone", "either"],
    "both": ["dual", "two", "pair", "together", "mutually", "jointly"],
    "none": ["nothing", "zero", "nil", "null", "nonexistent", "not any"],
    "often": ["frequently", "regularly", "commonly", "habitually", "repeatedly"],
    "rarely": ["seldom", "infrequently", "occasionally", "sporadically", "barely"],
    "soon": ["shortly", "presently", "momentarily", "before long", "promptly"],
    "later": ["subsequently", "afterward", "eventually", "thereafter", "following"],
    "now": ["currently", "presently", "at present", "right now", "immediately"],
    "then": ["subsequently", "thereafter", "afterward", "at that time", "next"],
    "very": ["extremely", "exceedingly", "remarkably", "exceptionally", "highly"],
    "really": ["actually", "truly", "genuinely", "sincerely", "honestly", "absolutely"],
    "quite": ["fairly", "rather", "somewhat", "reasonably", "moderately", "relatively"],
    "almost": ["nearly", "practically", "virtually", "approximately", "roughly"],
    "also": ["additionally", "furthermore", "moreover", "likewise", "besides"],
    "well": ["satisfactorily", "properly", "adequately", "effectively", "competently"],
    "about": ["approximately", "roughly", "around", "nearly", "almost", "virtually"],
    "around": ["approximately", "roughly", "surrounding", "nearby", "about", "throughout"],
    "over": ["above", "across", "beyond", "throughout", "completed", "finished"],
    "under": ["below", "beneath", "underneath", "subjected to", "subordinate"],
    "above": ["over", "beyond", "superior to", "higher than", "exceeding"],
    "below": ["under", "beneath", "underneath", "inferior to", "lower"],
    "through": ["via", "by means of", "using", "throughout", "across"],
    "between": ["among", "amid", "intermediate", "midway", "in the middle"],
    "against": ["opposing", "opposite", "contrary to", "versus", "counter"],
    "during": ["throughout", "amid", "over", "through", "in the course of"],
    "without": ["lacking", "excluding", "minus", "absent", "free from"],
    "within": ["inside", "in", "internal", "throughout", "contained in"],
    "despite": ["notwithstanding", "regardless", "in spite of", "even with"],
    "ability": ["capability", "competence", "proficiency", "aptitude", "faculty", "capacity"],
    "access": ["admittance", "entry", "entrance", "approach", "gateway"],
    "action": ["activity", "movement", "operation", "process", "performance"],
    "advantage": ["benefit", "asset", "gain", "edge", "upper hand", "leverage"],
    "advice": ["guidance", "counsel", "recommendation", "suggestion", "direction"],
    "agreement": ["contract", "understanding", "accord", "settlement", "consensus"],
    "analysis": ["examination", "evaluation", "study", "review", "investigation"],
    "application": ["request", "submission", "implementation", "employment", "use"],
    "approval": ["authorization", "sanction", "endorsement", "ratification", "permission"],
    "assessment": ["evaluation", "appraisal", "analysis", "judgment", "rating"],
    "attention": ["focus", "notice", "awareness", "observation", "regard", "consideration"],
    "attitude": ["mindset", "outlook", "perspective", "stance", "inclination", "disposition"],
    "authority": ["power", "jurisdiction", "control", "rule", "command"],
    "background": ["history", "experience", "context", "upbringing", "past", "credentials"],
    "balance": ["equilibrium", "stability", "evenness", "harmony", "symmetry"],
    "barrier": ["obstacle", "block", "hindrance", "impediment", "obstruction", "hurdle"],
    "behavior": ["conduct", "manner", "action", "performance", "practice"],
    "belief": ["conviction", "faith", "trust", "confidence", "opinion", "persuasion"],
    "boundary": ["limit", "border", "edge", "frontier", "perimeter", "margin"],
    "campaign": ["drive", "effort", "movement", "initiative", "push", "crusade"],
    "capacity": ["capability", "competence", "aptitude", "facility", "potential"],
    "category": ["class", "group", "type", "classification", "division", "section"],
    "center": ["middle", "core", "heart", "hub", "focal point", "nucleus"],
    "challenge": ["difficulty", "obstacle", "problem", "test", "trial", "hardship"],
    "chance": ["opportunity", "prospect", "possibility", "likelihood", "probability"],
    "character": ["personality", "nature", "disposition", "temperament", "traits"],
    "choice": ["option", "selection", "alternative", "preference", "pick", "decision"],
    "claim": ["assertion", "declaration", "statement", "allegation", "contention"],
    "client": ["customer", "patron", "consumer", "buyer", "shopper", "user"],
    "collection": ["group", "set", "assembly", "gathering", "accumulation"],
    "commitment": ["dedication", "devotion", "obligation", "engagement", "responsibility"],
    "communication": ["exchange", "interaction", "conversation", "correspondence", "dialogue"],
    "community": ["society", "public", "neighborhood", "population", "collective"],
    "competition": ["contest", "rivalry", "tournament", "match", "race", "championship"],
    "concern": ["worry", "anxiety", "apprehension", "unease", "distress", "trouble"],
    "condition": ["state", "circumstance", "situation", "requirement", "provision"],
    "confidence": ["assurance", "certainty", "trust", "faith", "conviction", "poise"],
    "conflict": ["dispute", "disagreement", "clash", "struggle", "confrontation"],
    "connection": ["link", "tie", "bond", "relationship", "association", "affiliation"],
    "consequence": ["result", "outcome", "effect", "ramification", "aftermath"],
    "consideration": ["thought", "attention", "reflection", "deliberation", "contemplation"],
    "contact": ["communication", "connection", "interaction", "touch", "reach"],
    "content": ["substance", "material", "subject matter", "text", "information"],
    "context": ["circumstances", "background", "situation", "framework", "environment"],
    "contract": ["agreement", "deal", "arrangement", "understanding", "covenant", "pact"],
    "contribution": ["donation", "input", "participation", "gift", "offering", "addition"],
    "conversation": ["dialogue", "discussion", "talk", "exchange", "chat"],
    "cooperation": ["collaboration", "teamwork", "partnership", "unity", "assistance"],
    "country": ["nation", "state", "land", "territory", "realm", "kingdom"],
    "course": ["path", "route", "direction", "program", "curriculum", "series"],
    "creation": ["formation", "production", "invention", "establishment", "genesis"],
    "crime": ["offense", "violation", "felony", "misdemeanor", "wrongdoing"],
    "crisis": ["emergency", "disaster", "catastrophe", "calamity", "turmoil"],
    "criteria": ["standards", "benchmarks", "guidelines", "measures", "requirements"],
    "criticism": ["censure", "disapproval", "condemnation", "faultfinding", "judgment"],
    "culture": ["society", "customs", "traditions", "heritage", "way of life"],
    "current": ["present", "ongoing", "contemporary", "prevailing", "topical", "existing"],
    "customer": ["client", "consumer", "patron", "buyer", "shopper", "purchaser"],
    "damage": ["harm", "injury", "destruction", "impairment", "detriment"],
    "danger": ["risk", "hazard", "threat", "peril", "jeopardy", "menace"],
    "deal": ["agreement", "transaction", "arrangement", "bargain", "compact"],
    "death": ["demise", "passing", "end", "expiration", "destruction"],
    "debate": ["discussion", "argument", "dispute", "discourse", "deliberation"],
    "debt": ["obligation", "liability", "arrears", "dues", "indebtedness", "balance"],
    "decision": ["choice", "determination", "resolution", "ruling", "verdict"],
    "decline": ["decrease", "reduction", "downturn", "drop", "fall", "descent"],
    "defense": ["protection", "security", "safeguard", "shield", "guard", "resistance"],
    "definition": ["meaning", "description", "interpretation", "explanation", "clarification"],
    "degree": ["level", "extent", "grade", "intensity", "measure", "magnitude"],
    "demand": ["request", "requirement", "need", "desire", "call", "insistence"],
    "department": ["division", "section", "unit", "branch", "segment", "office"],
    "description": ["account", "depiction", "portrayal", "representation", "summary"],
    "design": ["plan", "blueprint", "layout", "scheme", "composition", "arrangement"],
    "desire": ["wish", "longing", "yearning", "aspiration", "ambition", "craving"],
    "destination": ["target", "goal", "objective", "aim", "end point", "terminus"],
    "determination": ["resolve", "persistence", "perseverance", "dedication", "tenacity"],
    "development": ["progress", "advancement", "growth", "evolution", "improvement"],
    "device": ["gadget", "appliance", "instrument", "tool", "apparatus"],
    "difference": ["distinction", "disparity", "contrast", "divergence", "discrepancy"],
    "direction": ["guidance", "leadership", "management", "supervision", "instruction"],
    "disaster": ["catastrophe", "calamity", "cataclysm", "tragedy", "misfortune"],
    "discipline": ["regulation", "control", "order", "training", "practice"],
    "discovery": ["finding", "revelation", "breakthrough", "innovation", "uncovering"],
    "discussion": ["conversation", "dialogue", "debate", "exchange", "discourse"],
    "disease": ["illness", "sickness", "ailment", "infection", "disorder"],
    "display": ["exhibition", "show", "demonstration", "presentation", "exposition"],
    "dispute": ["argument", "debate", "controversy", "disagreement", "conflict"],
    "distance": ["length", "span", "stretch", "gap", "interval", "extent"],
    "distribution": ["allocation", "dispersion", "dissemination", "circulation"],
    "diversity": ["variety", "difference", "multiformity", "assortment", "range"],
    "domain": ["area", "field", "realm", "sphere", "territory", "province"],
    "economy": ["system", "market", "financial system", "trade", "commerce", "industry"],
    "effort": ["endeavor", "attempt", "undertaking", "work", "exertion", "striving"],
    "element": ["component", "constituent", "part", "factor", "feature", "ingredient"],
    "emotion": ["feeling", "sentiment", "response", "affect", "passion", "sensation"],
    "emphasis": ["stress", "accent", "prominence", "importance", "weight"],
    "employee": ["worker", "staff", "personnel", "laborer", "staff member"],
    "employment": ["work", "job", "occupation", "profession", "career", "vocation"],
    "encouragement": ["support", "motivation", "inspiration", "prompting", "urging"],
    "enemy": ["adversary", "opponent", "foe", "antagonist", "rival", "competitor"],
    "energy": ["power", "vitality", "vigor", "force", "strength", "dynamism"],
    "engagement": ["participation", "involvement", "commitment", "interaction"],
    "enterprise": ["venture", "business", "undertaking", "project", "initiative"],
    "enthusiasm": ["passion", "eagerness", "excitement", "zeal", "fervor", "ardor"],
    "environment": ["surroundings", "setting", "conditions", "atmosphere", "ambiance"],
    "equipment": ["gear", "apparatus", "tools", "materials", "hardware"],
    "error": ["mistake", "fault", "inaccuracy", "blunder", "oversight", "misstep"],
    "establishment": ["institution", "organization", "enterprise", "foundation"],
    "estimate": ["approximation", "guess", "assessment", "evaluation", "appraisal"],
    "evaluation": ["assessment", "appraisal", "analysis", "review", "judgment", "rating"],
    "event": ["occurrence", "happening", "occasion", "circumstance", "episode"],
    "evidence": ["proof", "confirmation", "verification", "indication", "testimony"],
    "evolution": ["development", "progress", "advancement", "change", "transformation"],
    "examination": ["inspection", "study", "analysis", "survey", "review", "scrutiny"],
    "excellence": ["superiority", "quality", "distinction", "merit", "virtue"],
    "exception": ["exclusion", "anomaly", "irregularity", "deviation", "outlier"],
    "excess": ["surplus", "overflow", "extra", "overabundance", "profusion", "glut"],
    "exchange": ["swap", "trade", "barter", "transaction", "interchange"],
    "excitement": ["enthusiasm", "thrill", "eagerness", "anticipation", "exhilaration"],
    "exercise": ["activity", "training", "practice", "workout", "drill", "routine"],
    "existence": ["being", "presence", "actuality", "reality", "life", "continuation"],
    "expansion": ["growth", "increase", "extension", "development", "amplification"],
    "expectation": ["anticipation", "hope", "prospect", "assumption", "prediction"],
    "expense": ["cost", "charge", "fee", "payment", "expenditure", "outlay"],
    "expert": ["specialist", "authority", "professional", "master", "virtuoso"],
    "expertise": ["specialization", "proficiency", "competence", "knowledge", "mastery"],
    "explanation": ["clarification", "elucidation", "description", "interpretation"],
    "exploration": ["investigation", "examination", "study", "research", "survey"],
    "expression": ["demonstration", "manifestation", "indication", "representation"],
    "extent": ["degree", "magnitude", "scope", "range", "breadth", "scale"],
    "extreme": ["dire", "severe", "intense", "drastic", "radical", "excessive"],
    "facility": ["amenity", "resource", "feature", "provision", "service", "convenience"],
    "factor": ["element", "aspect", "component", "determinant", "variable", "influence"],
    "failure": ["mishap", "breakdown", "collapse", "malfunction", "defeat", "loss"],
    "faith": ["trust", "confidence", "belief", "conviction", "reliance", "credence"],
    "fashion": ["style", "trend", "vogue", "mode", "popularity", "craze"],
    "fate": ["destiny", "fortune", "kismet", "predestination", "outcome", "future"],
    "fault": ["flaw", "defect", "imperfection", "shortcoming", "weakness", "deficiency"],
    "feature": ["characteristic", "attribute", "trait", "property", "aspect"],
    "feedback": ["response", "input", "reaction", "comment", "critique", "evaluation"],
    "field": ["area", "domain", "realm", "sphere", "sector", "territory"],
    "figure": ["number", "amount", "value", "statistics", "data", "total"],
    "finance": ["funding", "capital", "money", "resources", "budget", "funds"],
    "finding": ["discovery", "revelation", "result", "conclusion", "observation"],
    "firm": ["company", "business", "enterprise", "organization", "corporation"],
    "fitness": ["health", "wellness", "vigor", "stamina", "strength", "conditioning"],
    "flexibility": ["adaptability", "adjustability", "versatility", "malleability"],
    "focus": ["concentration", "attention", "emphasis", "fixation", "core"],
    "force": ["power", "strength", "energy", "might", "intensity", "vigor"],
    "forecast": ["prediction", "projection", "outlook", "estimate", "anticipation"],
    "formation": ["creation", "establishment", "development", "generation", "composition"],
    "formula": ["method", "system", "procedure", "recipe", "blueprint", "approach"],
    "fortune": ["wealth", "riches", "prosperity", "affluence", "opulence", "abundance"],
    "foundation": ["base", "basis", "groundwork", "underpinning", "cornerstone"],
    "framework": ["structure", "system", "skeleton", "outline", "architecture"],
    "freedom": ["liberty", "independence", "autonomy", "sovereignty"],
    "friend": ["companion", "ally", "associate", "colleague", "confidant", "comrade"],
    "function": ["purpose", "role", "operation", "performance", "activity", "capacity"],
    "future": ["prospect", "outlook", "progression", "destiny", "fate"],
    "gain": ["profit", "benefit", "advantage", "increase", "growth", "advancement"],
    "gap": ["breach", "divide", "disparity", "difference", "discrepancy", "interval"],
    "generation": ["age group", "cohort", "era", "period", "phase", "production"],
    "gesture": ["action", "motion", "move", "signal", "indication", "expression"],
    "gift": ["present", "donation", "offering", "grant", "benefaction"],
    "government": ["administration", "authority", "regime", "rule", "governance"],
    "grade": ["level", "rank", "class", "standard", "quality", "rating"],
    "grant": ["award", "allocation", "subsidy", "scholarship", "endowment"],
    "gratitude": ["thanksgiving", "appreciation", "acknowledgment", "recognition"],
    "growth": ["expansion", "development", "progress", "advancement", "improvement"],
    "guarantee": ["warranty", "assurance", "pledge", "promise", "security", "certification"],
    "guide": ["leader", "escort", "conductor", "mentor", "counselor", "advisor"],
    "habit": ["custom", "practice", "routine", "tradition", "convention", "usage"],
    "happiness": ["joy", "contentment", "satisfaction", "bliss", "delight"],
    "harm": ["injury", "damage", "hurt", "impairment", "detriment", "affliction"],
    "harmony": ["accord", "concord", "unity", "agreement", "compatibility", "peace"],
    "hazard": ["risk", "danger", "threat", "peril", "menace", "jeopardy"],
    "healing": ["recovery", "recuperation", "rehabilitation", "therapy", "restoration"],
    "heart": ["core", "center", "hub", "essence", "soul", "spirit"],
    "height": ["stature", "altitude", "elevation", "prominence", "pinnacle", "apex"],
    "heritage": ["inheritance", "legacy", "tradition", "birthright", "patrimony"],
    "hero": ["protagonist", "champion", "conqueror", "courageous", "idol", "icon"],
    "hierarchy": ["ranking", "order", "gradation", "structure", "pecking order"],
    "history": ["record", "account", "chronicle", "narrative", "background", "story"],
    "holder": ["owner", "possessor", "bearer", "custodian", "keeper", "proprietor"],
    "home": ["residence", "dwelling", "house", "lodging", "habitat", "abode"],
    "honesty": ["truthfulness", "integrity", "sincerity", "candor", "probity"],
    "hope": ["aspiration", "ambition", "expectation", "desire", "wish", "optimism"],
    "horizon": ["skyline", "vista", "prospect", "outlook", "purview", "scope"],
    "house": ["dwelling", "residence", "home", "abode", "lodging", "domicile"],
    "abandon": ["desert", "forsake", "relinquish", "renounce", "surrender"],
    "absorb": ["assimilate", "incorporate", "integrate", "imbibe", "engross"],
    "accelerate": ["quicken", "speed up", "expedite", "hasten", "advance"],
    "accept": ["embrace", "welcome", "acknowledge", "recognize", "endorse", "adopt"],
    "accompany": ["escort", "attend", "follow", "go with", "convoy"],
    "accomplish": ["achieve", "attain", "realize", "fulfill", "complete", "execute"],
    "accumulate": ["amass", "assemble", "collect", "gather", "stockpile"],
    "acknowledge": ["admit", "recognize", "confess", "disclose", "reveal", "affirm"],
    "adapt": ["adjust", "modify", "alter", "conform", "acclimatize"],
    "adjust": ["modify", "regulate", "adapt", "correct", "fine-tune", "tweak"],
    "admire": ["appreciate", "respect", "esteem", "revere", "honor", "adore"],
    "admit": ["confess", "concede", "acknowledge", "allow", "grant", "recognize"],
    "adopt": ["embrace", "assume", "undertake", "espouse", "take on"],
    "advance": ["progress", "proceed", "move forward", "promote", "further"],
    "adverse": ["unfavorable", "harmful", "detrimental", "hostile", "antagonistic"],
    "advise": ["recommend", "suggest", "counsel", "guide", "direct", "caution"],
    "affect": ["influence", "impact", "alter", "modify", "shape", "sway"],
    "agree": ["concur", "consent", "assent", "accept", "approve", "harmonize"],
    "aim": ["target", "focus", "direct", "intend", "purpose", "aspire"],
    "allocate": ["assign", "distribute", "apportion", "allot", "designate"],
    "alter": ["change", "modify", "adjust", "revise", "amend", "transform"],
    "amend": ["revise", "correct", "modify", "improve", "rectify", "remedy"],
    "amuse": ["entertain", "delight", "divert", "please", "charm", "engage"],
    "announce": ["declare", "proclaim", "promulgate", "broadcast", "publish"],
    "appear": ["emerge", "arise", "materialize", "surface", "manifest", "occur"],
    "apply": ["implement", "exercise", "utilize", "employ", "execute", "enforce"],
    "appoint": ["designate", "assign", "nominate", "select", "choose", "name"],
    "appreciate": ["value", "treasure", "admire", "esteem", "cherish"],
    "approach": ["near", "approximate", "method", "technique", "strategy"],
    "approve": ["endorse", "sanction", "authorize", "ratify", "confirm", "validate"],
    "argue": ["debate", "dispute", "contend", "assert", "maintain", "reason"],
    "arrange": ["organize", "rearrange", "order", "position", "dispose"],
    "arrive": ["come", "appear", "enter", "reach", "show up", "turn up"],
    "articulate": ["express", "voice", "communicate", "utter", "verbalize"],
    "assemble": ["gather", "collect", "congregate", "converge", "convene"],
    "assert": ["declare", "affirm", "maintain", "contend", "proclaim", "insist"],
    "assign": ["allocate", "designate", "appoint", "delegate", "allot"],
    "assist": ["help", "aid", "support", "facilitate", "guide", "serve"],
    "associate": ["connect", "link", "relate", "affiliate", "identify", "pair"],
    "assume": ["suppose", "presume", "presuppose", "infer", "conjecture"],
    "assure": ["reassure", "guarantee", "promise", "confirm", "certify", "warrant"],
    "attach": ["connect", "fasten", "affix", "secure", "bind", "couple"],
    "attempt": ["try", "endeavor", "strive", "seek", "undertake", "venture"],
    "attend": ["participate", "be present", "join", "appear", "observe"],
    "attract": ["draw", "pull", "lure", "entice", "tempt", "captivate"],
    "avoid": ["evade", "shun", "dodge", "elude", "sidestep", "circumvent"],
    "bear": ["endure", "tolerate", "withstand", "sustain", "suffer", "abide"],
    "beat": ["defeat", "overcome", "overwhelm", "conquer", "vanquish", "subdue"],
    "beg": ["plead", "implore", "beseech", "entreat", "solicit"],
    "bend": ["curve", "crook", "twist", "flex", "contort", "deform"],
    "bind": ["tie", "fasten", "secure", "attach", "connect", "link"],
    "blend": ["mix", "combine", "merge", "fuse", "integrate", "unify"],
    "block": ["obstruct", "impede", "hinder", "thwart", "bar", "stymie"],
    "boost": ["raise", "lift", "increase", "elevate", "augment", "enhance"],
    "breach": ["break", "violation", "infringement", "rupture", "split"],
    "cease": ["stop", "halt", "discontinue", "terminate", "end", "conclude"],
    "clarify": ["elucidate", "illuminate", "explain", "interpret", "expound"],
    "coincide": ["concur", "correspond", "agree", "match", "align"],
    "collaborate": ["cooperate", "team up", "work together", "partner", "join forces"],
    "commence": ["begin", "start", "initiate", "launch", "embark on"],
    "compel": ["force", "obligate", "coerce", "drive", "pressure", "impel"],
    "compensate": ["reimburse", "repay", "remunerate", "recompense", "indemnify"],
    "compile": ["assemble", "collect", "gather", "accumulate", "amass"],
    "comply": ["obey", "follow", "conform", "adhere", "abide by", "respect"],
    "compose": ["create", "write", "draft", "formulate", "author", "produce"],
    "conceal": ["hide", "cover", "disguise", "mask", "obscure", "suppress"],
    "concentrate": ["focus", "center", "centralize", "consolidate", "gather"],
    "conclude": ["finish", "end", "complete", "terminate", "close", "wrap up"],
    "condemn": ["censure", "criticize", "denounce", "disapprove", "reprobate"],
    "conduct": ["perform", "execute", "carry out", "administer", "implement"],
    "confine": ["restrict", "limit", "restrain", "constrain", "bound"],
    "confront": ["face", "challenge", "oppose", "withstand", "encounter"],
    "connect": ["link", "join", "attach", "couple", "associate", "affiliate"],
    "conserve": ["preserve", "save", "protect", "maintain", "sustain"],
    "consist": ["comprise", "include", "contain", "be composed of", "be made up of"],
    "consolidate": ["combine", "unite", "merge", "amalgamate", "integrate"],
    "consult": ["confer", "discuss", "deliberate", "advise", "counsel"],
    "consume": ["use", "utilize", "expend", "deplete", "exhaust", "devour"],
    "contend": ["assert", "argue", "maintain", "claim", "hold", "believe"],
    "contract": ["shrink", "tighten", "constrict", "narrow", "reduce"],
    "contribute": ["donate", "submit", "provide", "supply", "furnish", "add"],
    "convey": ["communicate", "express", "transmit", "impart", "relay"],
    "convince": ["persuade", "assure", "reassure", "satisfy", "win over"],
    "coordinate": ["organize", "arrange", "manage", "orchestrate", "synchronize"],
    "cope": ["manage", "handle", "deal", "endure", "weather", "survive"],
    "correct": ["rectify", "fix", "remedy", "amend", "resolve", "right"],
    "correlate": ["correspond", "relate", "associate", "connect", "link"],
    "counter": ["oppose", "resist", "combat", "contradict", "refute"],
    "cultivate": ["foster", "nurture", "develop", "encourage", "promote"],
    "curb": ["restrict", "limit", "control", "check", "inhibit"],
    "deceive": ["mislead", "fool", "trick", "delude", "hoodwink"],
    "declare": ["announce", "proclaim", "state", "assert", "affirm"],
    "decline": ["decrease", "diminish", "wane", "dwindle", "recede", "shrink"],
    "decorate": ["adorn", "ornament", "embellish", "beautify", "garnish"],
    "dedicate": ["commit", "devote", "sacrifice", "allocate", "assign"],
    "defeat": ["beat", "overcome", "conquer", "vanquish", "triumph over"],
    "defend": ["protect", "safeguard", "shield", "guard", "preserve"],
    "defer": ["postpone", "delay", "suspend", "put off", "shelve"],
    "define": ["describe", "determine", "specify", "delineate", "characterize"],
    "defy": ["resist", "challenge", "confront", "disobey", "oppose"],
    "delegate": ["assign", "entrust", "depute", "commission", "authorize"],
    "deliberate": ["consider", "contemplate", "ponder", "reflect", "weigh"],
    "demonstrate": ["show", "display", "exhibit", "illustrate", "prove"],
    "depart": ["leave", "exit", "withdraw", "retreat", "go away"],
    "depict": ["portray", "represent", "illustrate", "delineate", "describe"],
    "deprive": ["strip", "divest", "deny", "dispossess", "rob"],
    "derive": ["obtain", "gain", "acquire", "extract", "procure"],
    "deserve": ["merit", "warrant", "earn", "justify", "rate"],
    "designate": ["assign", "appoint", "nominate", "name", "choose"],
    "detach": ["separate", "disconnect", "sever", "disengage", "unfasten"],
    "detain": ["hold", "restrain", "delay", "keep", "retain"],
    "detect": ["spot", "identify", "discern", "notice", "perceive"],
    "deter": ["discourage", "dissuade", "inhibit", "prevent", "hinder"],
    "detract": ["diminish", "lessen", "reduce", "lower", "decrease"],
    "devise": ["create", "invent", "design", "develop", "formulate"],
    "devote": ["dedicate", "commit", "surrender", "give", "apply"],
    "dictate": ["command", "order", "direct", "decree", "impose"],
    "differentiate": ["distinguish", "discriminate", "separate", "contrast"],
    "diffuse": ["spread", "disperse", "scatter", "circulate", "dissipate"],
    "digest": ["absorb", "assimilate", "process", "comprehend", "understand"],
    "diminish": ["decrease", "lessen", "reduce", "dwindle", "recede"],
    "disagree": ["differ", "dissent", "object", "oppose", "contradict"],
    "disappear": ["vanish", "fade", "dissolve", "evaporate", "recede"],
    "disclose": ["reveal", "divulge", "expose", "uncover", "share"],
    "discourage": ["dissuade", "deter", "inhibit", "dishearten", "daunt"],
    "discriminate": ["differentiate", "distinguish", "segregate", "separate"],
    "disguise": ["camouflage", "conceal", "hide", "mask", "cover up"],
    "dismiss": ["discharge", "release", "expel", "let go", "send away"],
    "displace": ["replace", "supplant", "dislodge", "oust", "remove"],
    "dispose": ["arrange", "place", "position", "set", "order"],
    "disregard": ["ignore", "overlook", "neglect", "dismiss", "bypass"],
    "disrupt": ["interrupt", "disturb", "upset", "disorder", "break up"],
    "dissolve": ["melt", "liquefy", "disintegrate", "dissipate", "break down"],
    "distinguish": ["differentiate", "discriminate", "identify", "recognize"],
    "distort": ["twist", "warp", "bend", "deform", "misrepresent"],
    "distract": ["divert", "disturb", "interrupt", "sideline", "draw away"],
    "distribute": ["allocate", "apportion", "dispense", "allocate", "deal"],
    "disturb": ["bother", "annoy", "upset", "perturb", "agitate"],
    "diverge": ["differ", "deviate", "depart", "vary", "separate"],
    "diversify": ["vary", "broaden", "expand", "extend", "widen"],
    "divert": ["redirect", "reroute", "deflect", "distract", "channel"],
    "dominate": ["control", "rule", "govern", "overshadow", "overpower"],
    "donate": ["contribute", "give", "pledge", "grant", "bestow"],
    "draft": ["compose", "write", "formulate", "prepare", "sketch"],
    "drain": ["deplete", "exhaust", "empty", "sap", "consume"],
    "dramatize": ["exaggerate", "overstate", "sensationalize", "amplify"],
    "dread": ["fear", "dread", "apprehend", "worry", "panic"],
    "dress": ["attire", "clothe", "garb", "apparel", "adorn"],
    "drift": ["float", "glide", "slide", "stray", "wandered"],
    "dwell": ["reside", "live", "inhabit", "lodge", "linger"],
    "ease": ["alleviate", "relieve", "soothe", "lessen", "reduce"],
    "echo": ["reflect", "resonate", "reverberate", "mirror", "repeat"],
    "eclipse": ["surpass", "outshine", "dwarf", "overshadow", "exceed"],
    "economize": ["save", "conserve", "budget", "scrimp", "cut back"],
    "edify": ["educate", "instruct", "enlighten", "teach", "inform"],
    "educate": ["teach", "instruct", "train", "enlighten", "school"],
    "elaborate": ["expand", "develop", "detail", "explain", "expound"],
    "elect": ["choose", "select", "vote", "pick", "opt for"],
    "elevate": ["raise", "lift", "promote", "upgrade", "advance"],
    "eliminate": ["remove", "eradicate", "extinguish", "delete", "erased"],
    "elucidate": ["clarify", "explain", "illuminate", "expound", "interpret"],
    "embark": ["begin", "start", "commence", "undertake", "launch"],
    "embody": ["represent", "personify", "manifest", "incarnate", "symbolize"],
    "embrace": ["hug", "clasp", "accept", "adopt", "welcome"],
    "emerge": ["appear", "surface", "arise", "materialize", "develop"],
    "emit": ["discharge", "release", "expel", "radiate", "exude"],
    "emphasize": ["stress", "accentuate", "highlight", "underscore", "spotlight"],
    "empower": ["authorize", "enable", "permit", "license", "allow"],
    "empty": ["vacate", "drain", "evacuate", "clear", "deplete"],
    "enable": ["allow", "permit", "facilitate", "empower", "authorize"],
    "enact": ["implement", "execute", "perform", "effectuate", "realize"],
    "encircle": ["surround", "encompass", "wrap", "enclose", "ring"],
    "enclose": ["surround", "encircle", "encase", "include", "envelop"],
    "encounter": ["meet", "face", "confront", "experience", "come across"],
    "encourage": ["motivate", "inspire", "stimulate", "urge", "prompt"],
    "endanger": ["imperil", "jeopardize", "compromise", "threaten", "risk"],
    "endorse": ["approve", "support", "back", "sanction", "advocate"],
    "endure": ["persevere", "withstand", "bear", "tolerate", "sustain"],
    "enforce": ["implement", "impose", "administer", "apply", "execute"],
    "engage": ["participate", "involve", "occupy", "absorb", "immerse"],
    "enhance": ["improve", "augment", "enrich", "boost", "amplify"],
    "enjoy": ["like", "appreciate", "relish", "savor", "delight in"],
    "enlarge": ["expand", "magnify", "amplify", "extend", "broaden"],
    "enlighten": ["illuminate", "educate", "inform", "edify", "teach"],
    "enlist": ["recruit", "enroll", "register", "conscript", "muster"],
    "enrich": ["enhance", "augment", "improve", "better", "upgrade"],
    "enroll": ["register", "sign up", "enlist", "enter", "join"],
    "ensue": ["follow", "result", "succeed", "occur", "arise"],
    "entail": ["involve", "require", "necessitate", "demand", "include"],
    "enter": ["access", "join", "penetrate", "insert", "go into"],
    "entertain": ["amuse", "delight", "divert", "engage", "distract"],
    "enthuse": ["excite", "inspire", "motivate", "stimulate", "energize"],
    "entitle": ["qualify", "authorize", "legitimize", "empower", "allow"],
    "entrench": ["establish", "ingrain", "instill", "embed", "root"],
    "enumerate": ["count", "list", "catalog", "itemize", "recite"],
    "envelop": ["enclose", "surround", "wrap", "enshroud", "cover"],
    "envision": ["imagine", "visualize", "conceive", "envisage", "picture"],
    "erase": ["delete", "remove", "eliminate", "expunge", "obliterate"],
    "erect": ["construct", "build", "raise", "establish", "set up"],
    "erode": ["deteriorate", "corrode", "wear away", "decay", "disintegrate"],
    "erupt": ["explode", "burst", "outburst", "flare", "break out"],
    "escape": ["flee", "abscond", "evade", "elude", "break free"],
    "escort": ["accompany", "guide", "conduct", "usher", "chaperone"],
    "essence": ["core", "heart", "soul", "substance", "nature"],
    "estimate": ["approximate", "evaluate", "gauge", "judge", "rate"],
    "evacuate": ["vacate", "leave", "abandon", "depart", "withdraw"],
    "evaluate": ["assess", "appraise", "judge", "rate", "estimate"],
    "evaporate": ["vaporize", "disappear", "dissipate", "fade", "melt away"],
    "even": ["level", "flush", "uniform", "regular", "smooth"],
    "eventual": ["ultimate", "final", "later", "subsequent", "ensuing"],
    "ever": ["always", "forever", "perpetually", "eternally", "constantly"],
    "evident": ["obvious", "clear", "apparent", "manifest", "discernable"],
    "evil": ["malevolent", "malicious", "vicious", "sinister", "wicked"],
    "evoke": ["elicit", "arouse", "provoke", "stir", "awaken"],
    "evolve": ["develop", "progress", "advance", "mature", "unfold"],
    "exact": ["precise", "accurate", "correct", "specific", "perfect"],
    "exaggerate": ["overstate", "magnify", "embellish", "amplify", "stretch"],
    "exalt": ["praise", "extol", "laud", "glorify", "acclaim"],
    "examine": ["inspect", "scrutinize", "analyze", "study", "probe"],
    "exceed": ["surpass", "outstrip", "transcend", "beat", "overtake"],
    "excel": ["outperform", "surpass", "shine", "distinguish", "stand out"],
    "except": ["excluding", "excluding", "barring", "save", "besides"],
    "excerpt": ["passage", "extract", "selection", "quotation", "snippet"],
    "excessive": ["extreme", "undue", "inordinate", "disproportionate", "overly"],
    "excite": ["stir", "arouse", "stimulate", "thrill", "energize"],
    "exclaim": ["shout", "cry", "call out", "blurt", "declare"],
    "exclude": ["omit", "bar", "eliminate", "ostracize", "except"],
    "execute": ["perform", "carry out", "implement", "accomplish", "fulfill"],
    "exempt": ["immune", "excused", "not liable", "free", "excepted"],
    "exhaust": ["deplete", "drain", "consume", "use up", "tire"],
    "exhibit": ["display", "show", "demonstrate", "present", "reveal"],
    "exile": ["banish", "expel", "deport", "oust", "ostracize"],
    "exist": ["live", "persist", "endure", "prevail", "subsist"],
    "exit": ["leave", "depart", "withdraw", "egress", "go out"],
    "expand": ["enlarge", "broaden", "extend", "dilate", "swell"],
    "expedite": ["hasten", "accelerate", "facilitate", "speed", "rush"],
    "expel": ["eject", "oust", "remove", "banish", "deport"],
    "expend": ["spend", "use", "consume", "disburse", "pay out"],
    "experiment": ["trial", "test", "pilot", "investigation", "trial run"],
    "expire": ["end", "lapse", "run out", "terminate", "cease"],
    "explicit": ["clear", "detailed", "specific", "precise", "unequivocal"],
    "exploit": ["utilize", "harness", "capitalize on", "leverage", "take advantage of"],
    "explore": ["investigate", "probe", "survey", "examine", "research"],
    "export": ["ship", "trade", "send", "transport", "sell abroad"],
    "expose": ["reveal", "uncover", "disclose", "unmask", "lay bare"],
    "expound": ["explain", "elaborate", "clarify", "describe", "delineate"],
    "extend": ["prolong", "lengthen", "expand", "stretch", "elongate"],
    "extract": ["remove", "withdraw", "pull", "draw", "derive"],
    "extradite": ["transfer", "rendition", "deport", "surrender", "hand over"],
    "extricate": ["free", "release", "disengage", "liberate", "rescue"],
    "exult": ["rejoice", "glory", "triumph", "delight", "celebrate"],
}


def classify_synonyms(word, syns):
    """Split synonyms into standard/fluent/formal/creative groups."""
    n = len(syns)
    half = max(1, n // 2)
    # synonyms are roughly ordered common->uncommon, so first half = fluent, last half = formal
    fluent = [s for s in syns[:half] if ' ' not in s]
    formal = [s for s in syns[half:] if ' ' not in s]
    creative = syns[1:] + syns[:1]  # rotate for different ordering

    return {
        "standard": list(syns),
        "fluent": fluent or syns[:half],
        "formal": formal or syns[-half:],
        "creative": creative,
    }


structured = {}
for word, syns in FLAT_THESAURUS.items():
    structured[word] = classify_synonyms(word, syns)

os.makedirs("static/data", exist_ok=True)
with open("static/data/thesaurus.json", "w", encoding="utf-8") as f:
    json.dump(structured, f, indent=1, ensure_ascii=False)

print(f"Thesaurus created with {len(structured)} entries")
total_syns = sum(len(v.get("standard", v)) for v in structured.values())
formal_syns = sum(len(v.get("formal", [])) for v in structured.values())
print(f"Total synonyms across all modes: ~{total_syns * 3}")
print(f"Formal synonyms: {formal_syns}")
