<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap | StoryBrain AI</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif; color: #444; margin: 0; padding: 2rem; background-color: #f8f9fa; }
          #content { max-width: 1000px; margin: 0 auto; background: #fff; padding: 2rem; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.08); }
          h1 { color: #1a202c; font-size: 28px; margin-bottom: 0.5rem; }
          p { color: #4a5568; font-size: 15px; margin-bottom: 2rem; border-bottom: 1px solid #e2e8f0; padding-bottom: 1rem; }
          a { color: #3182ce; text-decoration: none; font-weight: 500;}
          a:hover { text-decoration: underline; }
          table { width: 100%; border-collapse: collapse; font-size: 15px; }
          th { background-color: #f7fafc; padding: 14px; text-align: left; color: #2d3748; font-weight: 600; border-bottom: 2px solid #e2e8f0; }
          td { padding: 14px; border-bottom: 1px solid #edf2f7; color: #4a5568; }
          tr:nth-child(even) td { background-color: #fdfdfd; }
          tr:hover td { background-color: #f1f5f9; }
          .badge { display: inline-block; padding: 0.25em 0.6em; font-size: 0.75em; font-weight: 700; line-height: 1; text-align: center; white-space: nowrap; vertical-align: baseline; border-radius: 0.375rem; background-color: #e2e8f0; color: #4a5568; }
        </style>
      </head>
      <body>
        <div id="content">
          <h1>StoryBrain AI - XML Sitemap</h1>
          <p>
            Generated by <strong>StoryBrain AI</strong>, this is an XML Sitemap, meant for consumption by search engines.<br/>
            You can find more information about XML sitemaps on <a href="https://sitemaps.org">sitemaps.org</a>.<br/><br/>
            This sitemap contains <span class="badge"><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></span> URLs.
          </p>
          <table>
            <thead>
              <tr>
                <th>URL</th>
                <th>Priority</th>
                <th>Change Frequency</th>
                <th>Last Modified</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:urlset/sitemap:url">
                <tr>
                  <td>
                    <xsl:variable name="itemURL">
                      <xsl:value-of select="sitemap:loc"/>
                    </xsl:variable>
                    <a href="{$itemURL}">
                      <xsl:value-of select="sitemap:loc"/>
                    </a>
                  </td>
                  <td><xsl:value-of select="sitemap:priority"/></td>
                  <td><xsl:value-of select="sitemap:changefreq"/></td>
                  <td><xsl:value-of select="sitemap:lastmod"/></td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
