#!/usr/bin/env bash
# ============================================================
# cPanel Reverse Proxy Setup for StoryBrain AI
# Run AFTER app is running on port 8090.
#
# Usage:
#   ssh user@hostinger-vps
#   cd /opt/storybrain-ai
#   bash run.sh                    # First: install & start app
#   bash scripts/cpanel_proxy_setup.sh  # Then: configure proxy
#
# This creates an Apache config that cPanel WHM can use
# OR adds a ProxyPass entry in your cPanel-managed vhost.
# ============================================================
set -euo pipefail

DOMAIN="${1:-}"
APP_PORT="${PORT:-8090}"

if [ -z "$DOMAIN" ]; then
    echo ""
    echo "Usage: bash scripts/cpanel_proxy_setup.sh yourdomain.com"
    echo ""
    echo "This sets up Apache reverse proxy from your domain to localhost:$APP_PORT"
    exit 1
fi

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log_info()  { echo -e "${GREEN}[INFO]${NC}  $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# ─── cPanel vhost detection ────────────────────────────────
CPANEL_VHOST_DIR="/etc/apache2/conf.d/userdata/std/2_4"
USER_HOMEDIR="/home/$(whoami)"

# Try to find the domain's Apache config
APACHE_CONF=""
if [ -d "$CPANEL_VHOST_DIR" ]; then
    VHOST_FILE=$(find "$CPANEL_VHOST_DIR" -name "*${DOMAIN}*" -type f 2>/dev/null | head -1)
    if [ -n "$VHOST_FILE" ]; then
        APACHE_CONF="$VHOST_FILE"
    fi
fi

# ─── Create proxy config ───────────────────────────────────
PROXY_CONF="/etc/apache2/conf.d/userdata/std/2_4/$(whoami)/${DOMAIN}/storybrain-proxy.conf"

log_info "Setting up reverse proxy for $DOMAIN → localhost:$APP_PORT"

# Ensure Apache modules are enabled
sudo a2enmod proxy proxy_http proxy_wstunnel headers rewrite 2>/dev/null || true

# Create config file
sudo mkdir -p "$(dirname "$PROXY_CONF")"
sudo tee "$PROXY_CONF" > /dev/null <<APACHE
# ─── StoryBrain AI Reverse Proxy ──────────────────────────
# Auto-generated by scripts/cpanel_proxy_setup.sh
# Domain: $DOMAIN → localhost:$APP_PORT

<IfModule mod_proxy.c>
    ProxyPreserveHost On
    ProxyRequests Off

    # WebSocket support
    ProxyPass /ws ws://127.0.0.1:${APP_PORT}/ws
    ProxyPassReverse /ws ws://127.0.0.1:${APP_PORT}/ws

    # Main application
    ProxyPass / http://127.0.0.1:${APP_PORT}/
    ProxyPassReverse / http://127.0.0.1:${APP_PORT}/

    # Security headers
    Header always set X-Forwarded-For "%{REMOTE_ADDR}s"
    Header always set X-Forwarded-Proto "https"
</IfModule>

# Static file caching
<LocationMatch "^/static/">
    Header set Cache-Control "public, max-age=31536000, immutable"
</LocationMatch>

# Deny access to sensitive files
<LocationMatch "(\.env|\.git|venv|__pycache__)">
    Require all denied
</LocationMatch>
APACHE

log_info "Config created at: $PROXY_CONF"

# ─── Rebuild Apache config ─────────────────────────────────
log_info "Rebuilding Apache config..."
if command -v /scripts/rebuildhttpdconf >/dev/null 2>&1; then
    sudo /scripts/rebuildhttpdconf
elif command -v whm >/dev/null 2>&1; then
    sudo whm api1 rebuild_httpd_conf 2>/dev/null || true
fi

# Restart Apache
log_info "Restarting Apache..."
if command -v systemctl >/dev/null 2>&1; then
    sudo systemctl restart httpd 2>/dev/null || sudo systemctl restart apache2 2>/dev/null || true
else
    sudo service httpd restart 2>/dev/null || sudo service apache2 restart 2>/dev/null || true
fi

log_info "=== Reverse proxy setup complete! ==="
log_info "Your app should be live at: https://$DOMAIN"
echo ""
log_warn "If it doesn't work, verify your cPanel 'Document Root' is set to:"
log_warn "  /opt/storybrain-ai/static"
log_warn "Or check Apache error log: tail -50 /etc/apache2/logs/error_log"
